stages:
  - prepare
  - linting
  - validate
  - build
  - deploy

variables:
  NODE_ENV: "test"

include:
  - local: .gitlab/ci/shellcheck.gitlab-ci.yml
  - local: wordpress/olecasinos.com/infrastructure/.gitlab-ci.yml
