image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest
variables:
  TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${CI_PROJECT_NAME}-olecasinos
  TF_ROOT: ${CI_PROJECT_DIR}/wordpress/olecasinos.com/infrastructure

cache:
  key: ${CI_COMMIT_REF_SLUG}-terraform-cache
  paths:
    - ${TF_ROOT}/.terraform

before_script:
  - cd ${TF_ROOT}

init:
  stage: prepare
  script:
    - gitlab-terraform init

validate:
  stage: validate
  script:
    - gitlab-terraform init
    - gitlab-terraform validate

plan:
  stage: build
  script:
    - gitlab-terraform plan
    - gitlab-terraform plan-json
  artifacts:
    name: plan
    paths:
      - ${TF_ROOT}/plan.cache
    reports:
      terraform: ${TF_ROOT}/plan.json

apply:
  stage: deploy
  environment:
    name: production
  script:
    - gitlab-terraform apply
  dependencies:
    - plan
